scan_timeout = 60
add_newline = false

[character]
success_symbol = "[➜](bold green)"

[line_break]
disabled = true

[directory]
style = "bold blue"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$status]($style) "

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
